### ISSUE TITLE
How to authenticate to a gateway?

### ISSUE THREAD

**Issue by thugic** [gr8shivam/laravel-sms-api#12]
Hey there,

before trying this packages I had a brief look through the code, and seems like there is no authentication implemented.

My SMS gateway sends a "user_key" and "Session_key" after sending a request to a specific endpoint (with a username and password), and these keys are required when sending requests to the SMS sending endpoint.

What would be the best way to implement authentication using your package?

Thanks

**Comment by gr8shivam** [comment]
Hi @thugic 

You can send the request directly and then use authenticated instance variables to send the request like:

```smsapi()->sendMessage("TO", "Message", ["user_key" => "val","session_key" => "val"]);```

I've added this to my to-do list and auth mechanism should be available in the next release. Also, please mention the SMS Gateway you're using.

**Comment by thugic** [comment]
Thanks for your answer. I'm using Skebby SMS gateway.

I created a helper class for sending through their API.

**Comment by gr8shivam** [comment]
As I checked, your gateway provides two auth methods:

1. Using a temporary session key, which expires after a certain amount of time 
2. Using an authentication token, which does not expire

Using the second auth method, you can send a GET request through Browser/Postman like :

```https://api.skebby.it/API/v1.0/REST/token?username=MY_USERNAME&password=MY_PASSWORD```

Followed by copying the returned USER_KEY and ACCESS_TOKEN and using it directly in the Gateway configuration.

**Comment by gr8shivam** [comment]
Here's a sample config for your gateway. Give this a try:

```
//    Gateway Configuration
    'skebby' => [
        'method' => 'POST',
        'url' => 'https://api.skebby.it/API/v1.0/REST/sms', 
        'params' => [
            'send_to_param_name' => 'recipient', //Send to Parameter Name
            'msg_param_name' => 'message', //Message Parameter Name
            'others' => [
                'sender' => 'MySender',
                'returnCredits' => 'true',
                //More params can be added
            ],
        ],
        'headers' => [
            'user_key' => 'USER_KEY',
            'Access_token' => 'ACCESS_TOKEN',
        ],
       'json' => true,
        'add_code' => false,
    ],
```

Then use the following code to send the SMS:

```
$recipients = ["+393471234567","+393471234568"];

$message = "Hello world!";

smsapi()->gateway('skebby')->sendMessage($recipients, $message, ["message_type" => "XX"]);

//OR smsapi()->gateway('skebby')->sendMessage($recipients, $message, ["scheduled_delivery_time" => "XX", "message_type" => "XX"]);

```

**Comment by thugic** [comment]
Neat!
Thanks for your efforts!

**Comment by adeyemiokeowo** [comment]
Hi,
Really love your SMS Api for Laravel, have been stock trying to integrate my SMS APi, 
please look into my API here;
i used this very well in PHP, now i want to apply it in Laravel. please help

function send_sms($sms, $sendto, $sender)
{
    $dnr = $sendto;
    $sessionid = 'SESSION ID';
    /* call the URL */
    $url = "http://www.smslive247.com/http/index.aspx?"
        . "cmd=sendmsg"
        . "&sessionid=" . UrlEncode($sessionid)
        . "&message=" . UrlEncode($sms)
        . "&sender=" . UrlEncode($sender)
        . "&sendto=" . UrlEncode($sendto);
    if ($f = @fopen($url, "r")) {
        $answer = fgets($f, 255);
        if (substr($answer, 0, 1) == "+") {
            echo "successful sent to ".$dnr;
        } else {
            $message= "Successfully Sent: [$answer].";
        }
    } else {
         $message= "Error: URL could not be opened.";
    }
	Return $message;
}
