### ISSUE TITLE
Having issue using Sms Api laravel

### ISSUE THREAD

**Issue by adeyemiokeowo** [gr8shivam/laravel-sms-api#13]
Hi,
Really love your SMS Api for Laravel, have been stock trying to integrate my SMS APi,
please look into my API here;
i used this very well in PHP, now i want to apply it in Laravel. please help

function send_sms($sms, $sendto, $sender)
{
$dnr = $sendto;
$sessionid = 'SESSION ID';
/* call the URL */
$url = "http://www.smslive247.com/http/index.aspx?"
. "cmd=sendmsg"
. "&sessionid=" . UrlEncode($sessionid)
. "&message=" . UrlEncode($sms)
. "&sender=" . UrlEncode($sender)
. "&sendto=" . UrlEncode($sendto);
if ($f = @fopen($url, "r")) {
$answer = fgets($f, 255);
if (substr($answer, 0, 1) == "+") {
echo "successful sent to ".$dnr;
} else {
$message= "Successfully Sent: [$answer].";
}
} else {
$message= "Error: URL could not be opened.";
}
Return $message;
}

**Comment by gr8shivam** [comment]
Hi @adeyemiokeowo 

You can try the following config:-

```
    'smslive247' => [
        'url' => 'http://www.smslive247.com/http/index.aspx?',
        'params' => [
            'send_to_param_name' => 'sendto', //Send to Parameter Name
            'msg_param_name' => 'message', //Message Parameter Name
            'others' => [
                'cmd' => 'sendmsg', 
            ],
        ],
        'add_code' => false, //Include Country Code
    ],
```

To send message, use:

```
smsapi()->gateway('smslive247')->sendMessage($sendto, $sms, ["sessionid" => $sessionid, "sender" => $sender]);
```

**Comment by adeyemiokeowo** [comment]
Hi,
Many thanks really appreciate it works greatly.

**Comment by gr8shivam** [comment]
Glad to help! Please Star the repo to show Support :)
