### ISSUE TITLE
I have trouble with neogate tg100 SMS Gateway

### ISSUE THREAD

**Issue by dardangashi** [gr8shivam/laravel-sms-api#14]
With neogate tg100 is very simple to send sms via browser or with php code. with browser i send sms like this : http://[IP]/cgi/WebCGI?1500101=account=[user]&password=[pass]&port=[port]&destination=[phone_number]&content=[MSG] . but in laravel with sms api i can not send sms. Thank you for your contributions.

**Comment by gr8shivam** [comment]
The URL isn't following the standard HTTP query parameter pattern.

Try using this config:

```
    'neotag_tg100' => [
        'url' => 'http://[IP]/cgi/WebCGI?1500101=',
        'params' => [
            'send_to_param_name' => 'destination', //Send to Parameter Name
            'msg_param_name' => 'content', //Message Parameter Name
            'others' => [
                'account' => '[user]',
                'password' => '[pass]',
                'port' => '[port]',
            ],
        ],
        'add_code' => false,
    ],
```

Usage:
`smsapi()->gateway('neotag_tg100')->sendMessage("TO", "Message");`

**Comment by dardangashi** [comment]
> The URL isn't following the standard HTTP query parameter pattern.
> 
> Try using this config:
> 
> ```
>     'neotag_tg100' => [
>         'url' => 'http://[IP]/cgi/WebCGI?1500101=',
>         'params' => [
>             'send_to_param_name' => 'destination', //Send to Parameter Name
>             'msg_param_name' => 'content', //Message Parameter Name
>             'others' => [
>                 'account' => '[user]',
>                 'password' => '[pass]',
>                 'port' => '[port]',
>             ],
>         ],
>         'add_code' => false,
>     ],
> ```
> 
> Usage:
> `smsapi()->gateway('neotag_tg100')->sendMessage("TO", "Message");`

not working with Neogate TG100 i have testet with this config but dd return this response

`-response: """
    <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    \t<head>
    \t\t<title>onLogout</title>
    \t\t<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    \t\t<script src="../js/import.js"></script>
    \t\t<script type="text/javascript">
    \t\t\tfunction onLogout(){\t
    \t\t\t\tparent.location.href = G_SERVER_ROOT;
    \t\t\t}
    \t\t\twindow.onload = onLogout;
    \t\t</script>
    \t</head>
    \t<body>
    \t</body>
    </html>
    """`
i think this is content of function logout

**Comment by gr8shivam** [comment]
You need to use a manual curl request since the url doesn't follow the standard HTTP query parameter pattern.
