### ISSUE TITLE
Failing to sending msg when content more than words.

### ISSUE THREAD

**Issue by kabircse** [gr8shivam/laravel-sms-api#15]
I am trying to implement your package with larvel 6, but this package fails to send SMS when the message body contains more than one word. 

No problem at single words. I am waiting for your response.

**Comment by gr8shivam** [comment]
Can you please your implementation, inlcuding the config and function call. Make sure to mask the API keys (wherever applicable).

**Comment by kabircse** [comment]
Thanks for your reply, Maybe the problem in my message server. Using curl, I get the same situation. 
After changing my message server, I will inform you, what will happen.

**Comment by kabircse** [comment]
That was my message server problem, your code is ok. Thanks for this package.
