### ISSUE TITLE
Issue to send an SMS with link embedded

### ISSUE THREAD

**Issue by scramatte** [gr8shivam/laravel-sms-api#17]
Hello,

First of all , thank you for  your lib that saves me lot of time.
It works well :)

Now I'm trying to send a link into body of SMS. Our Provider offer us such feature.
https://panel.smspubli.com/api/3.0/docs/link/send

If I send an SMS with basic PHP code without any framework as on their webpage it works.
But it doesn't works with your module.  I think it's probably due  to  "{" and "}" chars but I'm unable to debug it. 

Moreover  I need to pass dynamically  link URL to the json payload. How can I achieve this.
Please take a look to their manual and told me how can I get it running.

Thank you very much.

**Comment by gr8shivam** [comment]
Hi @scramatte 

Why are you not using "Send SMS" as per your provider? (https://panel.smspubli.com/api/3.0/docs/sms/send)

You can include the link within the message text.

**Comment by gr8shivam** [comment]
@scramatte Is the issue resolved now?

**Comment by gr8shivam** [comment]
Closing the issue. Reopen if the issue still exists.
