### ISSUE TITLE
sending sms from laravel controller 

### ISSUE THREAD

**Issue by maxlyh93** [gr8shivam/laravel-sms-api#21]
Hi, I am trying out your package. However I cant seem to get the code working not sure if im doing it right or not.... I am testing using postman. Below is the gateway config. then the controller, then the api. and finally the sms api documentation im using

'country_code' => '60', //Country code to be added
    'default' => env('SMS_API_DEFAULT_GATEWAY', 'sms123'), //Choose default gateway
    
    'sms123' => [
        'method' => 'GET', //Choose Request Method (GET/POST)
        'url' => 'https://www.sms123.net/api/send.php?', //Base URL
        'params' => [
            'send_to_param_name' => 'recipients', //Send to Parameter Name
            'msg_param_name' => 'messageContent', //Message Parameter Name
            'others' => [
                'apiKey' => 'MY_API_KEY', //Your auth key
                'referenceID' => '_MY_REF_ID',
            ],
        ],
        'json' => true, // Use if you want the params to be sent in JSON format instead of query params
        'wrapper' => 'sms', //Optional, use only if you want the JSON request to be wrapped
        'add_code' => false, //Include Country Code (true/false)
    ],

/////////////////CONTROLLER///////////////////
use SmsApi;

class SmsController extends ResponseController
{
    public function SendSMS(Request $request)
    {
        $response=SmsApi::gateway('sms123')->sendMessage("SOME_NUMBER", "GoShare S/B, chargeup.asia");
    }
}

//////////////API////////////
Route::post('sendsms','API\SmsController@SendSMS');

//////////SMS API documentation////////////
https://www.sms123.net/apiIntegration.php

**Comment by gr8shivam** [comment]
Try out this config:
```
'sms123' => [
    'method' => 'POST', 
    'url' => 'https://www.sms123.net/api/send.php?', 
    'params' => [
        'send_to_param_name' => 'recipients', 
        'msg_param_name' => 'messageContent',
        'others' => [
            'apiKey' => 'MY_API_KEY', //Your auth key
            'referenceID' => '_MY_REF_ID', // Your Ref ID
        ],
    ],
    'json' => false,
    'add_code' => true, //Include Country Code (true/false)
],
```

Note: If mobile numbers in your Database already have country code, change `add_code` to `false`.

**Comment by maxlyh93** [comment]
Amazing. the problem has been solved... THANKYOU so much!! why couldnt i send out messages earlier?

**Comment by gr8shivam** [comment]
You had json and wrapper options enabled, which weren't required as per your SMS provider format.

Star ⭐ this repo to show your support 😄

**Comment by gr8shivam** [comment]
@maxlyh93 One more remark, always remember to mask your API keys on public platforms. Happy coding 😄
