### ISSUE TITLE
How to manually upload into the Server

### ISSUE THREAD

**Issue by blpraveen** [gr8shivam/laravel-sms-api#22]
I am using hosting service provider to host the  website I dont have access to command prompt. I need to manually upload the files into the  server. Can You help me to setup the SMS API Plugin?

**Comment by gr8shivam** [comment]
It's outside the scope of this package. I can only provide you relevant links to proceed.

You can follow this: https://stackoverflow.com/a/44891109

Package Link: https://php-download.com/package/gr8shivam/laravel-sms-api
