### ISSUE TITLE
Facade dynamic using problem

### ISSUE THREAD

**Issue by emrebbozkurt** [gr8shivam/laravel-sms-api#29]
When i want to use with facade like `SmsApi::sendMessage("0XXXXXX", "Test")` giving the "Non-static method 'sendMessage' should not be called statically" error.

![image](https://user-images.githubusercontent.com/35993608/170485495-8e745e4a-2b82-4fd1-a40a-d35653602592.png)

**Comment by gr8shivam** [comment]
Thanks for reporting this. Will push an update to fix this.

**Comment by emrebbozkurt** [comment]
Thanks for reply I hope soon fixed.

**Comment by gr8shivam** [comment]
The issue is that you're explicitly providing the class to use. This stops Laravel from using the specified alias.

Remove the manual class import `use Gr8Shivam\SmsApi\SmsApi;` from your code and let Laravel do its magic.
