### ISSUE TITLE
Am having trouble to use Text Local can you help to set textlocal gate way 

### ISSUE THREAD

**Issue by DevaraneniKarthik** [gr8shivam/laravel-sms-api#5]

**Comment by gr8shivam** [comment]
Hi Karthik, you need to open the `config/sms-api.php` file and set the configuration. 

```
//   Sample Gateway Configuration
    'gateway_name' => [
        'url' => 'BaseUrl', //Base URL
        'params' => [
            'send_to_param_name' => '', //Send to Parameter Name
            'msg_param_name' => '', //Message Parameter Name
            'others' => [
                'param1' => '',
                'param2' => '',
                'param3' => '',
                //More params can be added
            ],
        ],
        'add_code' => true, //Include Country Code (true/false)
    ],
```

In the above sample configuration,
1. You need to replace the `'gateway_name'` with any name you like for example `'textlocal'`.
2. Next you need to put the `BaseUrl` which is the API url without including any params.
3. For each operator, the "send to" parameter name differs, thus add that parameter name as value for `'send_to_param_name'` key. Similarly, do the same for `'msg_param_name'` key.
4. If there are any other parameters to be included like api key or username, include them in `'others'` as a key-value pair.
5. If the operator wants you to include country code, change `'add_code'` to true else false. By default, it uses 91 as `'country_code'`

**Comment by DevaraneniKarthik** [comment]
Thanks, Shivam

Will Try And Let you know 🙂

**Comment by DevaraneniKarthik** [comment]
Hey,
Shivam

there might be a problem I tried to figure but I cant.
It is showing an empty response.

No Errors Nor No Exceptions Being thrown.

Any Help Greatly Appreciated.

Thanks,
Karthik

**Comment by DevaraneniKarthik** [comment]
Now When I print The Response It is showing

public function sendMessage($to, $message, $extra_params=null) {
if($this->gateway==''){
$this->loadDefaultGateway();
}
$this->loadCredentialsFromConfig();
$mobile = $this->config['add_code']?$this->addCountryCode($to):$to;
if(is_array($mobile)){
$mobile = $this->composeBulkMobile($mobile);
}
try {
$this->response = $this->getClient()->get($this->getUrl
($mobile,$message,$extra_params))->getBody()->getContents();
} catch (RequestException $e) {
if ($e->hasResponse()) {
$this->response = $e->getResponseBodySummary($e->getResponse());
}
}
print_r('SMS Gateway Response: '.$this->response);
exit;
Log::info('SMS Gateway Response: '.$this->response);
return $this;
}


SMS Gateway Response: {"type":"error","message":"Missing Authentication
Key","code":"106"}

**Comment by gr8shivam** [comment]
Are you specifying the gateway name while using? If not, change the default gateway in `config/sms-api.php`:

`'default' => env('SMS_API_DEFAULT_GATEWAY', 'msg91'), //Choose default gateway`

**Comment by DevaraneniKarthik** [comment]
protected function loadCredentialsFromConfig() {
$gateway = $this->gateway;
$config_name = 'sms-api.'.$gateway; // Problem was here changed to
$config_name = 'sms-api.textlocal'; //gateway configuration working good
$this->config = config($config_name);
return $this;
}


Thanks,
 Shivam Agrawal,
what you did is incredible Code is Amazing exactly what I need.

The Way you responded is super and thanks for all what have you done.

I was very much impressed with you and your Work  willing to be in touch
with you
if interested can you please share you mobile num and linked in profile.

so that we will be in contact and expand our Work.

**Comment by DevaraneniKarthik** [comment]
yes Will do in that way

**Comment by gr8shivam** [comment]
Great!

Also, thanks a lot for the appreciation. You can star ⭐️ this repository for giving repo 🥇

**Comment by DevaraneniKarthik** [comment]
Yeah sure, Can you share your  linked in profile

if interested your number also...

**Comment by gr8shivam** [comment]
Sure, here you go: https://in.linkedin.com/in/gr8shivam
